# Generated by Django 5.0.6 on 2024-07-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='seatAllocation',
            field=models.JSONField(default=dict),
        ),
    ]
