# Generated by Django 5.0.6 on 2024-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_management', '0002_show_seatallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
