# Generated by Django 5.0.6 on 2024-07-10 12:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('PROCESSING', 'Order Processing'), ('FAILED', 'booking Failed'), ('COMPLETE', 'Booking Complete'), ('CANCELLED', 'Booking Cancelled')], default='PROCESSING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.TextField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('SUCCESS', 'Success')], default='PENDING', max_length=20),
        ),
    ]
