# Generated by Django 5.0.6 on 2024-07-15 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0002_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-id']},
        ),
    ]
