# Generated by Django 5.0.6 on 2024-07-15 12:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_code',
            field=models.TextField(default=uuid.uuid4),
        ),
    ]
