# Generated by Django 5.0.6 on 2024-07-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_management', '0004_ticket_ticket_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_code',
        ),
    ]
