# Generated by Django 5.0.6 on 2024-06-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='phone',
            field=models.CharField(max_length=120),
        ),
    ]
