# Generated by Django 5.0.6 on 2024-06-11 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_management', '0003_screentype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_seats', models.IntegerField(max_length=50)),
                ('screen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_type', to='theater_management.screentype')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater', to='theater_management.theater')),
            ],
        ),
    ]
