# Generated by Django 5.0.6 on 2024-06-11 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_management', '0004_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='screen_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theater_management.screentype'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theater_management.theater'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='total_seats',
            field=models.IntegerField(),
        ),
    ]
