# Generated by Django 5.0.6 on 2024-06-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_management', '0005_alter_screen_screen_type_alter_screen_theater_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='theater_status',
            field=models.CharField(choices=[('APPROVED', 'Theater Was Approved'), ('PENDING', 'Theater is Pending for Approval'), ('REJECTED', 'Theater is Rejected by JustBook')], default='PENDING', max_length=10),
        ),
    ]
