# Generated by Django 5.0.6 on 2024-06-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_management', '0007_seat_type_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='longitude',
        ),
        migrations.AddField(
            model_name='theater',
            name='address',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='theater',
            name='state',
            field=models.TextField(default=' '),
        ),
    ]
