# Generated by Django 5.0.6 on 2024-07-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_management', '0009_remove_seats_row_remove_seats_seat_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_allocation',
            field=models.JSONField(default={}),
        ),
    ]
