# Generated by Django 5.0.6 on 2024-07-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_management', '0010_alter_seats_seat_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='seat_allocation',
            field=models.JSONField(default=dict),
        ),
    ]
