# Generated by Django 5.0.6 on 2024-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_management', '0011_alter_seats_seat_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='no_of_screens',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
